{"dependencies": [{"name": "aiofiles", "version": "24.1.0", "vulns": []}, {"name": "aiohappyeyeballs", "version": "2.6.1", "vulns": []}, {"name": "aiohttp", "version": "3.12.15", "vulns": []}, {"name": "aioredis", "version": "2.0.1", "vulns": []}, {"name": "aioresponses", "version": "0.7.8", "vulns": []}, {"name": "aiosignal", "version": "1.4.0", "vulns": []}, {"name": "altgraph", "version": "0.17.2", "vulns": []}, {"name": "annotated-types", "version": "0.7.0", "vulns": []}, {"name": "anyio", "version": "4.10.0", "vulns": []}, {"name": "argcomplete", "version": "3.6.2", "vulns": []}, {"name": "asttokens", "version": "3.0.0", "vulns": []}, {"name": "async-timeout", "version": "5.0.1", "vulns": []}, {"name": "asyncio-throttle", "version": "1.0.2", "vulns": []}, {"name": "attrs", "version": "25.3.0", "vulns": []}, {"name": "autoflake", "version": "2.3.1", "vulns": []}, {"name": "backports-asyncio-runner", "version": "1.2.0", "vulns": []}, {"name": "backports-tarfile", "version": "1.2.0", "vulns": []}, {"name": "bandit", "version": "1.8.6", "vulns": []}, {"name": "beautifulsoup4", "version": "4.13.4", "vulns": []}, {"name": "black", "version": "23.12.1", "vulns": [{"id": "PYSEC-2024-48", "fix_versions": ["24.3.0"], "aliases": ["CVE-2024-21503"], "description": "Versions of the package black before 24.3.0 are vulnerable to Regular Expression Denial of Service (ReDoS) via the lines_with_leading_tabs_expanded function in the strings.py file. An attacker could exploit this vulnerability by crafting a malicious input that causes a denial of service.\r\rExploiting this vulnerability is possible when running Black on untrusted input, or if you habitually put thousands of leading tab characters in your docstrings."}]}, {"name": "bleach", "version": "6.2.0", "vulns": []}, {"name": "boolean-py", "version": "5.0", "vulns": []}, {"name": "build", "version": "1.3.0", "vulns": []}, {"name": "cachecontrol", "version": "0.14.3", "vulns": []}, {"name": "certifi", "version": "2025.8.3", "vulns": []}, {"name": "cfgv", "version": "3.4.0", "vulns": []}, {"name": "charset-normalizer", "version": "3.4.3", "vulns": []}, {"name": "click", "version": "8.1.8", "vulns": []}, {"name": "codecov-cli", "version": "11.1.0", "vulns": []}, {"name": "colorama", "version": "0.4.6", "vulns": []}, {"name": "commitizen", "version": "4.8.3", "vulns": []}, {"name": "coverage", "version": "7.10.5", "vulns": []}, {"name": "cyclonedx-python-lib", "version": "9.1.0", "vulns": []}, {"name": "decli", "version": "0.6.3", "vulns": []}, {"name": "decorator", "version": "5.2.1", "vulns": []}, {"name": "defusedxml", "version": "0.7.1", "vulns": []}, {"name": "detect-secrets", "version": "1.5.0", "vulns": []}, {"name": "distlib", "version": "0.4.0", "vulns": []}, {"name": "docutils", "version": "0.22", "vulns": []}, {"name": "dparse", "version": "0.6.4", "vulns": []}, {"name": "exceptiongroup", "version": "1.3.0", "vulns": []}, {"name": "executing", "version": "2.2.0", "vulns": []}, {"name": "factory-boy", "version": "3.3.3", "vulns": []}, {"name": "faker", "version": "37.5.3", "vulns": []}, {"name": "filelock", "version": "3.19.1", "vulns": []}, {"name": "freezegun", "version": "1.5.5", "vulns": []}, {"name": "frozenlist", "version": "1.7.0", "vulns": []}, {"name": "future", "version": "0.18.2", "vulns": [{"id": "PYSEC-2022-42991", "fix_versions": ["0.18.3"], "aliases": ["CVE-2022-40899"], "description": "An issue discovered in Python Charmers Future 0.18.2 and earlier allows remote attackers to cause a denial of service via crafted Set-Cookie header from malicious web server."}, {"id": "GHSA-xqrq-4mgf-ff32", "fix_versions": [], "aliases": ["CVE-2025-50817"], "description": "A vulnerability in the Python-Future 1.0.0 module allows for arbitrary code execution via the unintended import of a file named test.py. When the module is loaded, it automatically imports test.py, if present in the same directory or in the sys.path. This behavior can be exploited by an attacker who has the ability to write files to the server, allowing the execution of arbitrary code."}]}, {"name": "h11", "version": "0.16.0", "vulns": []}, {"name": "h2", "version": "4.3.0", "vulns": []}, {"name": "hiredis", "version": "3.2.1", "vulns": []}, {"name": "hpack", "version": "4.1.0", "vulns": []}, {"name": "httpcore", "version": "1.0.9", "vulns": []}, {"name": "httpx", "version": "0.28.1", "vulns": []}, {"name": "hyperframe", "version": "6.1.0", "vulns": []}, {"name": "hypothesis", "version": "6.138.3", "vulns": []}, {"name": "identify", "version": "2.6.13", "vulns": []}, {"name": "idna", "version": "3.10", "vulns": []}, {"name": "ijson", "version": "3.4.0", "vulns": []}, {"name": "importlib-metadata", "version": "8.6.1", "vulns": []}, {"name": "iniconfig", "version": "2.1.0", "vulns": []}, {"name": "ipdb", "version": "0.13.13", "vulns": []}, {"name": "ipython", "version": "8.18.1", "vulns": []}, {"name": "isort", "version": "5.13.2", "vulns": []}, {"name": "jaraco-classes", "version": "3.4.0", "vulns": []}, {"name": "jaraco-context", "version": "6.0.1", "vulns": []}, {"name": "jaraco-functools", "version": "4.3.0", "vulns": []}, {"name": "jedi", "version": "0.19.2", "vulns": []}, {"name": "jinja2", "version": "3.1.6", "vulns": []}, {"name": "jschema-to-python", "version": "1.2.3", "vulns": []}, {"name": "jsonpickle", "version": "4.1.1", "vulns": []}, {"name": "keyring", "version": "25.6.0", "vulns": []}, {"name": "license-expression", "version": "30.4.4", "vulns": []}, {"name": "line-profiler", "version": "4.2.0", "vulns": []}, {"name": "lxml", "version": "6.0.1", "vulns": []}, {"name": "macholib", "version": "1.15.2", "vulns": []}, {"name": "markdown-it-py", "version": "3.0.0", "vulns": []}, {"name": "markupsafe", "version": "3.0.2", "vulns": []}, {"name": "matplotlib-inline", "version": "0.1.7", "vulns": []}, {"name": "mdurl", "version": "0.1.2", "vulns": []}, {"name": "memory-profiler", "version": "0.61.0", "vulns": []}, {"name": "more-itertools", "version": "10.7.0", "vulns": []}, {"name": "msgpack", "version": "1.1.1", "vulns": []}, {"name": "multidict", "version": "6.6.4", "vulns": []}, {"name": "mypy", "version": "1.17.1", "vulns": []}, {"name": "mypy-extensions", "version": "1.1.0", "vulns": []}, {"name": "nh3", "version": "0.3.0", "vulns": []}, {"name": "nodeenv", "version": "1.9.1", "vulns": []}, {"name": "packageurl-python", "version": "0.17.5", "vulns": []}, {"name": "packaging", "version": "25.0", "vulns": []}, {"name": "parso", "version": "0.8.5", "vulns": []}, {"name": "pathspec", "version": "0.12.1", "vulns": []}, {"name": "pbr", "version": "7.0.1", "vulns": []}, {"name": "pexpect", "version": "4.9.0", "vulns": []}, {"name": "pi", "version": "0.1.2", "vulns": []}, {"name": "pip", "version": "21.2.4", "vulns": [{"id": "PYSEC-2023-228", "fix_versions": ["23.3"], "aliases": ["CVE-2023-5752"], "description": "When installing a package from a Mercurial VCS URL  (ie \"pip install  hg+...\") with pip prior to v23.3, the specified Mercurial revision could  be used to inject arbitrary configuration options to the \"hg clone\"  call (ie \"--config\"). Controlling the Mercurial configuration can modify  how and which repository is installed. This vulnerability does not  affect users who aren't installing from Mercurial. "}]}, {"name": "pip-api", "version": "0.0.34", "vulns": []}, {"name": "pip-audit", "version": "2.9.0", "vulns": []}, {"name": "pip-requirements-parser", "version": "32.0.1", "vulns": []}, {"name": "pkginfo", "version": "1.12.1.2", "vulns": []}, {"name": "platformdirs", "version": "4.3.8", "vulns": []}, {"name": "pluggy", "version": "1.6.0", "vulns": []}, {"name": "pre-commit", "version": "3.8.0", "vulns": []}, {"name": "prompt-toolkit", "version": "3.0.51", "vulns": []}, {"name": "propcache", "version": "0.3.2", "vulns": []}, {"name": "psutil", "version": "5.9.8", "vulns": []}, {"name": "ptyprocess", "version": "0.7.0", "vulns": []}, {"name": "pure-eval", "version": "0.2.3", "vulns": []}, {"name": "py-cpuinfo", "version": "9.0.0", "vulns": []}, {"name": "py-serializable", "version": "2.1.0", "vulns": []}, {"name": "pydantic", "version": "2.11.7", "vulns": []}, {"name": "pydantic-core", "version": "2.33.2", "vulns": []}, {"name": "pyflakes", "version": "3.4.0", "vulns": []}, {"name": "pygments", "version": "2.19.2", "vulns": []}, {"name": "pyjwt", "version": "2.10.1", "vulns": []}, {"name": "pyparsing", "version": "3.2.3", "vulns": []}, {"name": "pyproject-hooks", "version": "1.2.0", "vulns": []}, {"name": "pytest", "version": "7.4.4", "vulns": []}, {"name": "pytest-asyncio", "version": "0.23.8", "vulns": []}, {"name": "pytest-benchmark", "version": "4.0.0", "vulns": []}, {"name": "pytest-cov", "version": "4.1.0", "vulns": []}, {"name": "pytest-mock", "version": "3.14.1", "vulns": []}, {"name": "python-dateutil", "version": "2.9.0.post0", "vulns": []}, {"name": "pyyaml", "version": "6.0.2", "vulns": []}, {"name": "questionary", "version": "2.1.0", "vulns": []}, {"name": "readme-renderer", "version": "44.0", "vulns": []}, {"name": "redis", "version": "5.3.1", "vulns": []}, {"name": "requests", "version": "2.32.4", "vulns": []}, {"name": "requests-toolbelt", "version": "1.0.0", "vulns": []}, {"name": "responses", "version": "0.21.0", "vulns": []}, {"name": "rfc3986", "version": "2.0.0", "vulns": []}, {"name": "rich", "version": "13.9.4", "vulns": []}, {"name": "ruamel-yaml", "version": "0.18.15", "vulns": []}, {"name": "ruamel-yaml-clib", "version": "0.2.12", "vulns": []}, {"name": "ruff", "version": "0.12.10", "vulns": []}, {"name": "safety", "version": "2.3.4", "vulns": []}, {"name": "sarif-om", "version": "1.0.4", "vulns": []}, {"name": "sentry-sdk", "version": "2.35.0", "vulns": []}, {"name": "setuptools", "version": "58.0.4", "vulns": [{"id": "PYSEC-2022-43012", "fix_versions": ["65.5.1"], "aliases": ["CVE-2022-40897"], "description": "Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py."}, {"id": "PYSEC-2025-49", "fix_versions": ["78.1.1"], "aliases": ["CVE-2025-47273", "GHSA-5rjg-fvgr-3xxf"], "description": "setuptools is a package that allows users to download, build, install, upgrade, and uninstall Python packages. A path traversal vulnerability in `PackageIndex` is present in setuptools prior to version 78.1.1. An attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to remote code execution depending on the context. Version 78.1.1 fixes the issue."}]}, {"name": "six", "version": "1.15.0", "vulns": []}, {"name": "sniffio", "version": "1.3.1", "vulns": []}, {"name": "sortedcontainers", "version": "2.4.0", "vulns": []}, {"name": "soupsieve", "version": "2.7", "vulns": []}, {"name": "stack-data", "version": "0.6.3", "vulns": []}, {"name": "stevedore", "version": "5.5.0", "vulns": []}, {"name": "structlog", "version": "23.3.0", "vulns": []}, {"name": "tenacity", "version": "8.5.0", "vulns": []}, {"name": "termcolor", "version": "3.1.0", "vulns": []}, {"name": "test-results-parser", "version": "0.5.4", "vulns": []}, {"name": "toml", "version": "0.10.2", "vulns": []}, {"name": "tomli", "version": "2.2.1", "vulns": []}, {"name": "tomlkit", "version": "0.13.3", "vulns": []}, {"name": "traitlets", "version": "5.14.3", "vulns": []}, {"name": "twine", "version": "4.0.2", "vulns": []}, {"name": "types-beautifulsoup4", "version": "4.12.0.20250516", "vulns": []}, {"name": "types-html5lib", "version": "1.1.11.20250809", "vulns": []}, {"name": "types-pyyaml", "version": "6.0.12.20250822", "vulns": []}, {"name": "types-requests", "version": "2.32.4.20250809", "vulns": []}, {"name": "typing-extensions", "version": "4.14.1", "vulns": []}, {"name": "typing-inspection", "version": "0.4.1", "vulns": []}, {"name": "tzdata", "version": "2025.2", "vulns": []}, {"name": "urllib3", "version": "2.5.0", "vulns": []}, {"name": "virtualenv", "version": "20.34.0", "vulns": []}, {"name": "wcwidth", "version": "0.2.13", "vulns": []}, {"name": "webencodings", "version": "0.5.1", "vulns": []}, {"name": "wheel", "version": "0.37.0", "vulns": [{"id": "PYSEC-2022-43017", "fix_versions": ["0.38.1"], "aliases": ["CVE-2022-40898"], "description": "An issue discovered in Python Packaging Authority (PyPA) Wheel 0.37.1 and earlier allows remote attackers to cause a denial of service via attacker controlled input to wheel cli."}]}, {"name": "yarl", "version": "1.20.1", "vulns": []}, {"name": "zipp", "version": "3.23.0", "vulns": []}], "fixes": []}
